spring.application.name=NextRole

spring.datasource.url=jdbc:postgresql://localhost:5432/NextRoleDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PW}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

stripe.secret=${STRIPE_SECRET}

stripe.product=${STRIPE_PRODUCT_KEY}
stripe.price=${STRIPE_PRICE_KEY}
jwt.key=${JWT_KEY}

aws.s3.bucket=${S3_NAME}

logging.level.org.springframework.security=DEBUG
