spring.application.name=NextRole

spring.datasource.url=jdbc:postgresql://localhost:5432/NextRoleDB
spring.datasource.username=postgres
spring.datasource.password=${DB_PW}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

stripe.secret=${STRIPE_SECRET}

stripe.product=${STRIPE_PRODUCT_KEY}
stripe.price=${STRIPE_PRICE_KEY}
jwt.key=${JWT_KEY}

aws.s3.bucket=${S3_NAME}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG
