export enum MessageTypes{
    SUGGESTION = 'SUGGESTION',
    BUG = 'BUG',
    FEEDBACK = 'FEEDBACK',
    QUESTION = 'QUESTION',
    FEATURE_REQUEST = 'FEATURE_REQUEST',
    COMPLAINTS = 'COMPLAINTS'
}